name: Code Verification (CI)

# Step 1: When should it run?
on: [push, pull_request]

# Step 2: Which runner do we use and what steps do we execute?
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clones the repository code into the virtual machine
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Installs clang on the cloud Linux runner
      - name: Install clang
        run: sudo apt-get update && sudo apt-get install -y clang-format

      # Run clang on bye.c to check for linter errors
      - name: Run clang
        run: clang-format --dry-run -Werror c-bye/bye.c
